name: pos_inventario_offline
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ✅ Base de datos SQL embebida (SQLite integrado)
  sqflite: ^2.3.3
  path_provider: ^2.1.4
  path: ^1.9.0

  # ✅ Seguridad (hash + almacenamiento seguro)
  crypto: ^3.0.5
  flutter_secure_storage: ^9.2.2

  # ✅ ids únicos para registros
  uuid: ^4.5.1

  # ✅ Imágenes (galería / cámara)
  image_picker: ^1.1.2

  # ✅ PARTE 5: Backup/Restore (zip) + seleccionar archivo + compartir
  archive: ^3.6.1
  file_picker: ^8.1.2
  share_plus: ^10.0.2

  # ✅ PARTE 6: Generar PDF + Vista previa/Impresión
  pdf: ^3.10.8
  printing: ^5.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
